# Generated by Django 5.2.6 on 2025-10-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_description_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('farmer', 'Farmer'), ('vendor', 'Vendor')], default='farmer', max_length=15),
        ),
    ]
